In [1]:
#Import packages
import pandas as pd
import numpy as np

In [2]:
#import dataset
df = pd.read_csv('World_Development_Indicators.csv')

In [3]:
#panel data
df.head()

,Country Name,Country Code,Series Name,Series Code,1980 [YR1980],1981 [YR1981],1982 [YR1982],1983 [YR1983],1984 [YR1984],1985 [YR1985],...,2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017]
0,Afghanistan,AFG,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,153.0526,154.1398,155.227,156.3758,157.5246,158.6734,...,111.4708,105.5516,99.6324,93.7132,87.794,82.2638,76.7336,71.2034,..,..
1,Afghanistan,AFG,Adults (ages 15+) and children (ages 0-14) new...,SH.HIV.INCD.TL,..,..,..,..,..,..,...,1000,1000,1000,1000,1000,1000,1000,1000,1000,..
2,Afghanistan,AFG,Adults (ages 15+) newly infected with HIV,SH.HIV.INCD,..,..,..,..,..,..,...,1000,1000,1000,1000,1000,1000,1000,1000,1000,..
3,Afghanistan,AFG,Age dependency ratio (% of working-age populat...,SP.POP.DPND,93.64624765,94.74081583,95.62039013,96.31070958,96.98459637,97.90473471,...,100.6564961,100.7408126,100.4064115,98.73075897,96.52858984,94.00173412,91.37620486,88.76872734,86.57093215,..
4,Afghanistan,AFG,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,4.675707137,4.736705879,4.745468538,4.69428943,4.575061337,4.376627085,...,4.520404759,4.56695004,4.615930641,4.645107387,4.672895042,4.695393129,4.706918195,4.7062685,4.741807624,..

In [4]:
#check data type and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59928 entries, 0 to 59927
Data columns (total 42 columns):
Country Name     59928 non-null object
Country Code     59928 non-null object
Series Name      59928 non-null object
Series Code      59928 non-null object
1980 [YR1980]    59928 non-null object
1981 [YR1981]    59928 non-null object
1982 [YR1982]    59928 non-null object
1983 [YR1983]    59928 non-null object
1984 [YR1984]    59928 non-null object
1985 [YR1985]    59928 non-null object
1986 [YR1986]    59928 non-null object
1987 [YR1987]    59928 non-null object
1988 [YR1988]    59928 non-null object
1989 [YR1989]    59928 non-null object
1990 [YR1990]    59928 non-null object
1991 [YR1991]    59928 non-null object
1992 [YR1992]    59928 non-null object
1993 [YR1993]    59928 non-null object
1994 [YR1994]    59928 non-null object
1995 [YR1995]    59928 non-null object
1996 [YR1996]    59928 non-null object
1997 [YR1997]    59928 non-null object
1998 [YR1998]    59928 non-null object
1999 [YR1999]    59928 non-null object
2000 [YR2000]    59928 non-null object
2001 [YR2001]    59928 non-null object
2002 [YR2002]    59928 non-null object
2003 [YR2003]    59928 non-null object
2004 [YR2004]    59928 non-null object
2005 [YR2005]    59928 non-null object
2006 [YR2006]    59928 non-null object
2007 [YR2007]    59928 non-null object
2008 [YR2008]    59928 non-null object
2009 [YR2009]    59928 non-null object
2010 [YR2010]    59928 non-null object
2011 [YR2011]    59928 non-null object
2012 [YR2012]    59928 non-null object
2013 [YR2013]    59928 non-null object
2014 [YR2014]    59928 non-null object
2015 [YR2015]    59928 non-null object
2016 [YR2016]    59928 non-null object
2017 [YR2017]    59928 non-null object
dtypes: object(42)
memory usage: 19.2+ MB

In [5]:
#change .. to NaN
df.replace('..',np.nan, inplace = True)
df.head()

,Country Name,Country Code,Series Name,Series Code,1980 [YR1980],1981 [YR1981],1982 [YR1982],1983 [YR1983],1984 [YR1984],1985 [YR1985],...,2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017]
0,Afghanistan,AFG,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,153.0526,154.1398,155.227,156.3758,157.5246,158.6734,...,111.4708,105.5516,99.6324,93.7132,87.794,82.2638,76.7336,71.2034,NaN,NaN
1,Afghanistan,AFG,Adults (ages 15+) and children (ages 0-14) new...,SH.HIV.INCD.TL,NaN,NaN,NaN,NaN,NaN,NaN,...,1000,1000,1000,1000,1000,1000,1000,1000,1000,NaN
2,Afghanistan,AFG,Adults (ages 15+) newly infected with HIV,SH.HIV.INCD,NaN,NaN,NaN,NaN,NaN,NaN,...,1000,1000,1000,1000,1000,1000,1000,1000,1000,NaN
3,Afghanistan,AFG,Age dependency ratio (% of working-age populat...,SP.POP.DPND,93.64624765,94.74081583,95.62039013,96.31070958,96.98459637,97.90473471,...,100.6564961,100.7408126,100.4064115,98.73075897,96.52858984,94.00173412,91.37620486,88.76872734,86.57093215,NaN
4,Afghanistan,AFG,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,4.675707137,4.736705879,4.745468538,4.69428943,4.575061337,4.376627085,...,4.520404759,4.56695004,4.615930641,4.645107387,4.672895042,4.695393129,4.706918195,4.7062685,4.741807624,NaN

In [6]:
# missing values per years
df.isnull().sum() #missing values

Country Name         0
Country Code         0
Series Name          0
Series Code          0
1980 [YR1980]    41320
1981 [YR1981]    41254
1982 [YR1982]    41048
1983 [YR1983]    41222
1984 [YR1984]    41087
1985 [YR1985]    40977
1986 [YR1986]    40736
1987 [YR1987]    40344
1988 [YR1988]    40771
1989 [YR1989]    40584
1990 [YR1990]    33612
1991 [YR1991]    35698
1992 [YR1992]    35012
1993 [YR1993]    35280
1994 [YR1994]    35290
1995 [YR1995]    32776
1996 [YR1996]    32708
1997 [YR1997]    32281
1998 [YR1998]    32507
1999 [YR1999]    32376
2000 [YR2000]    24163
2001 [YR2001]    28822
2002 [YR2002]    28453
2003 [YR2003]    28559
2004 [YR2004]    28450
2005 [YR2005]    26059
2006 [YR2006]    27265
2007 [YR2007]    27717
2008 [YR2008]    27860
2009 [YR2009]    27089
2010 [YR2010]    23819
2011 [YR2011]    26975
2012 [YR2012]    27061
2013 [YR2013]    27132
2014 [YR2014]    27497
2015 [YR2015]    26404
2016 [YR2016]    38116
2017 [YR2017]    59436
dtype: int64

In [7]:
# if there are 35 Nans in a row, drop the row(series)
df.dropna(thresh=35, axis=0, inplace=True)

In [8]:
# drop repeated columns
# drop the 2017 column since most of the values are missing
df.drop('2017 [YR2017]', axis=1, inplace=True)
df.head()

,Country Name,Country Code,Series Name,Series Code,1980 [YR1980],1981 [YR1981],1982 [YR1982],1983 [YR1983],1984 [YR1984],1985 [YR1985],...,2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016]
0,Afghanistan,AFG,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,153.0526,154.1398,155.227,156.3758,157.5246,158.6734,...,117.39,111.4708,105.5516,99.6324,93.7132,87.794,82.2638,76.7336,71.2034,NaN
3,Afghanistan,AFG,Age dependency ratio (% of working-age populat...,SP.POP.DPND,93.64624765,94.74081583,95.62039013,96.31070958,96.98459637,97.90473471,...,100.2310231,100.6564961,100.7408126,100.4064115,98.73075897,96.52858984,94.00173412,91.37620486,88.76872734,86.57093215
4,Afghanistan,AFG,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,4.675707137,4.736705879,4.745468538,4.69428943,4.575061337,4.376627085,...,4.473363168,4.520404759,4.56695004,4.615930641,4.645107387,4.672895042,4.695393129,4.706918195,4.7062685,4.741807624
5,Afghanistan,AFG,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,88.97054052,90.00410995,90.8749216,91.61642015,92.40953503,93.52810763,...,95.75765997,96.13609132,96.17386254,95.79048088,94.08565158,91.85569479,89.30634099,86.66928666,84.06245884,81.82912453
9,Afghanistan,AFG,"Birth rate, crude (per 1,000 people)",SP.DYN.CBRT.IN,50.596,50.493,50.388,50.277,50.157,50.022,...,42.86,41.697,40.474,39.232,38.016,36.863,35.797,34.836,33.98,NaN

In [9]:
#change data type from object to numeric 
col_names = ['1980 [YR1980]', '1981 [YR1981]',
       '1982 [YR1982]', '1983 [YR1983]', '1984 [YR1984]', '1985 [YR1985]',
       '1986 [YR1986]', '1987 [YR1987]', '1988 [YR1988]', '1989 [YR1989]',
       '1990 [YR1990]', '1991 [YR1991]', '1992 [YR1992]', '1993 [YR1993]',
       '1994 [YR1994]', '1995 [YR1995]', '1996 [YR1996]', '1997 [YR1997]',
       '1998 [YR1998]', '1999 [YR1999]', '2000 [YR2000]', '2001 [YR2001]',
       '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]',
       '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]', '2009 [YR2009]',
       '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]',
       '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]']

df[col_names] = df[col_names].apply(pd.to_numeric, errors='coerce')

#check data type 
df.dtypes.head()

Country Name      object
Country Code      object
Series Name       object
Series Code       object
1980 [YR1980]    float64
dtype: object

In [10]:
#change column names
col_names2 = ['Country Name','Country Code','Series Name','Series Code','1980', '1981',  '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
             '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
             '2009', '2010','2011', '2012', '2013', '2014', '2015', '2016']

df.columns = col_names2

In [11]:
df.isnull().sum()

Country Name       0
Country Code       0
Series Name        0
Series Code        0
1980             451
1981             348
1982             291
1983             208
1984             138
1985              53
1986              12
1987               3
1988               1
1989               0
1990               0
1991               2
1992              16
1993              16
1994              16
1995               1
1996               0
1997               0
1998               1
1999               1
2000               3
2001               1
2002               1
2003               1
2004               8
2005               7
2006               2
2007               2
2008               4
2009               6
2010               1
2011               5
2012              71
2013              80
2014             104
2015             172
2016            2724
dtype: int64

In [12]:
df_copy = df.fillna(method='pad', axis=1)

In [13]:
df_copy.drop('1980', axis=1, inplace=True)

In [14]:
df = pd.merge(df, df_copy, left_index=True, right_index=True)

In [15]:
df.columns

Index(['Country Name_x', 'Country Code_x', 'Series Name_x', 'Series Code_x',
       '1980', '1981_x', '1982_x', '1983_x', '1984_x', '1985_x', '1986_x',
       '1987_x', '1988_x', '1989_x', '1990_x', '1991_x', '1992_x', '1993_x',
       '1994_x', '1995_x', '1996_x', '1997_x', '1998_x', '1999_x', '2000_x',
       '2001_x', '2002_x', '2003_x', '2004_x', '2005_x', '2006_x', '2007_x',
       '2008_x', '2009_x', '2010_x', '2011_x', '2012_x', '2013_x', '2014_x',
       '2015_x', '2016_x', 'Country Name_y', 'Country Code_y', 'Series Name_y',
       'Series Code_y', '1981_y', '1982_y', '1983_y', '1984_y', '1985_y',
       '1986_y', '1987_y', '1988_y', '1989_y', '1990_y', '1991_y', '1992_y',
       '1993_y', '1994_y', '1995_y', '1996_y', '1997_y', '1998_y', '1999_y',
       '2000_y', '2001_y', '2002_y', '2003_y', '2004_y', '2005_y', '2006_y',
       '2007_y', '2008_y', '2009_y', '2010_y', '2011_y', '2012_y', '2013_y',
       '2014_y', '2015_y', '2016_y'],
      dtype='object')

In [16]:
df.drop(['1981_x', '1982_x', '1983_x', '1984_x', '1985_x', '1986_x',
       '1987_x', '1988_x', '1989_x', '1990_x', '1991_x', '1992_x', '1993_x',
       '1994_x', '1995_x', '1996_x', '1997_x', '1998_x', '1999_x', '2000_x',
       '2001_x', '2002_x', '2003_x', '2004_x', '2005_x', '2006_x', '2007_x',
       '2008_x', '2009_x', '2010_x', '2011_x', '2012_x', '2013_x', '2014_x',
       '2015_x', '2016_x', 'Country Name_y', 'Country Code_y', 'Series Name_y',
       'Series Code_y'], axis=1, inplace=True)

In [17]:
df.columns

Index(['Country Name_x', 'Country Code_x', 'Series Name_x', 'Series Code_x',
       '1980', '1981_y', '1982_y', '1983_y', '1984_y', '1985_y', '1986_y',
       '1987_y', '1988_y', '1989_y', '1990_y', '1991_y', '1992_y', '1993_y',
       '1994_y', '1995_y', '1996_y', '1997_y', '1998_y', '1999_y', '2000_y',
       '2001_y', '2002_y', '2003_y', '2004_y', '2005_y', '2006_y', '2007_y',
       '2008_y', '2009_y', '2010_y', '2011_y', '2012_y', '2013_y', '2014_y',
       '2015_y', '2016_y'],
      dtype='object')

In [18]:
df.columns.value_counts().sum()

41

In [19]:
df.columns = col_names2

In [20]:
df = df.fillna(method='bfill', axis=1)

In [21]:
df.isnull().sum()

Country Name    0
Country Code    0
Series Name     0
Series Code     0
1980            0
1981            0
1982            0
1983            0
1984            0
1985            0
1986            0
1987            0
1988            0
1989            0
1990            0
1991            0
1992            0
1993            0
1994            0
1995            0
1996            0
1997            0
1998            0
1999            0
2000            0
2001            0
2002            0
2003            0
2004            0
2005            0
2006            0
2007            0
2008            0
2009            0
2010            0
2011            0
2012            0
2013            0
2014            0
2015            0
2016            0
dtype: int64

In [22]:
df

,Country Name,Country Code,Series Name,Series Code,1980,1981,1982,1983,1984,1985,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Afghanistan,AFG,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,153.053,154.14,155.227,156.376,157.525,158.673,...,117.39,111.471,105.552,99.6324,93.7132,87.794,82.2638,76.7336,71.2034,71.2034
3,Afghanistan,AFG,Age dependency ratio (% of working-age populat...,SP.POP.DPND,93.6462,94.7408,95.6204,96.3107,96.9846,97.9047,...,100.231,100.656,100.741,100.406,98.7308,96.5286,94.0017,91.3762,88.7687,86.5709
4,Afghanistan,AFG,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,4.67571,4.73671,4.74547,4.69429,4.57506,4.37663,...,4.47336,4.5204,4.56695,4.61593,4.64511,4.6729,4.69539,4.70692,4.70627,4.74181
5,Afghanistan,AFG,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,88.9705,90.0041,90.8749,91.6164,92.4095,93.5281,...,95.7577,96.1361,96.1739,95.7905,94.0857,91.8557,89.3063,86.6693,84.0625,81.8291
9,Afghanistan,AFG,"Birth rate, crude (per 1,000 people)",SP.DYN.CBRT.IN,50.596,50.493,50.388,50.277,50.157,50.022,...,42.86,41.697,40.474,39.232,38.016,36.863,35.797,34.836,33.98,33.98
29,Afghanistan,AFG,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,22.298,21.673,21.021,20.344,19.65,18.943,...,9.108,8.742,8.403,8.095,7.816,7.563,7.331,7.118,6.924,6.924
39,Afghanistan,AFG,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.449,7.449,7.45,7.452,7.455,7.458,...,6.46,6.254,6.038,5.816,5.595,5.38,5.174,4.981,4.802,4.802
48,Afghanistan,AFG,"Immunization, DPT (% of children ages 12-23 mo...",SH.IMM.IDPT,4,3,5,5,16,15,...,63,64,63,66,68,67,64,62,65,65
50,Afghanistan,AFG,"Immunization, measles (% of children ages 12-2...",SH.IMM.MEAS,11,11,8,9,14,14,...,55,59,60,62,64,59,57,60,62,62
65,Afghanistan,AFG,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,42.705,43.369,44.08,44.837,45.636,46.473,...,60.933,61.486,61.999,62.476,62.924,63.354,63.778,64.197,64.613,64.613
66,Afghanistan,AFG,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,41.085,41.738,42.432,43.164,43.93,44.728,...,58.543,59.086,59.589,60.054,60.484,60.892,61.286,61.67,62.046,62.046
67,Afghanistan,AFG,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,41.8752,42.5336,43.2359,43.9801,44.7622,45.5792,...,59.7089,60.2567,60.7646,61.2355,61.6742,62.093,62.5016,62.9027,63.2982,63.2982
75,Afghanistan,AFG,"Mortality rate, adult, female (per 1,000 femal...",SP.DYN.AMRT.FE,434.766,427.478,420.19,410.705,401.22,391.735,...,243.045,238.354,233.662,228.971,224.28,219.588,215.307,211.026,206.746,206.746
76,Afghanistan,AFG,"Mortality rate, adult, male (per 1,000 male ad...",SP.DYN.AMRT.MA,483.952,476.305,468.658,459.362,450.067,440.771,...,286.238,281.258,276.279,271.299,266.32,261.34,257.135,252.93,248.724,248.724
77,Afghanistan,AFG,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,163.3,158.9,154.4,149.8,145.6,141.3,...,73.4,70.8,68.2,65.7,63.3,61,58.8,56.8,54.9,53.2
81,Afghanistan,AFG,"Mortality rate, under-5 (per 1,000 live births)",SH.DYN.MORT,244.8,238.2,231.5,224.6,217.9,210.9,...,102.2,98.2,94.1,90.2,86.4,82.8,79.3,76.1,73.2,70.4
85,Afghanistan,AFG,Newborns protected against tetanus (%),SH.VAC.TTNS.ZS,5,36,25,31,34,13,...,84,83,89,79,60,60,65,70,70,65
89,Afghanistan,AFG,Number of infant deaths,SH.DTH.IMRT,103367,99729,95662,91369,87367,83565,...,81908,79546,76883,74119,71359,68696,66203,64027,62058,60384
93,Afghanistan,AFG,Number of under-five deaths,SH.DTH.MORT,155713,150779,145174,139060,132967,126844,...,113091,109682,105715,101626,97426,93356,89403,85863,82759,79856
113,Afghanistan,AFG,Population ages 0-14 (% of total),SP.POP.0014.TO.ZS,45.9449,46.2174,46.4547,46.6691,46.9121,47.2592,...,47.8236,47.9108,47.9095,47.7981,47.3433,46.7391,46.0338,45.2874,44.532,43.8595
114,Afghanistan,AFG,"Population ages 0-14, female",SP.POP.0014.FE.IN,2.97864e+06,2.94869e+06,2.89045e+06,2.81722e+06,2.74976e+06,2.70671e+06,...,6.18323e+06,6.35936e+06,6.53067e+06,6.70266e+06,6.85341e+06,6.99164e+06,7.11592e+06,7.22529e+06,7.31836e+06,7.40053e+06
115,Afghanistan,AFG,"Population ages 0-14, female (% of total)",SP.POP.0014.FE.ZS,45.7449,45.9922,46.2053,46.3963,46.6186,46.951,...,47.9909,48.0345,47.9984,47.8575,47.4481,46.8839,46.2125,45.4962,44.7692,44.0728
116,Afghanistan,AFG,"Population ages 0-14, male",SP.POP.0014.MA.IN,3.10831e+06,3.08451e+06,3.03237e+06,2.96475e+06,2.9018e+06,2.86186e+06,...,6.54586e+06,6.71743e+06,6.88607e+06,7.06471e+06,7.21163e+06,7.35587e+06,7.49138e+06,7.60996e+06,7.70517e+06,7.79942e+06
117,Afghanistan,AFG,"Population ages 0-14, male (% of total)",SP.POP.0014.MA.ZS,46.1382,46.4347,46.6951,46.9315,47.1938,47.5543,...,47.6665,47.7943,47.8255,47.742,47.2441,46.6024,45.8654,45.0909,44.309,43.6589
118,Afghanistan,AFG,"Population ages 0-14, total",SP.POP.0014.TO,6.08695e+06,6.0332e+06,5.92281e+06,5.78196e+06,5.65155e+06,5.56857e+06,...,1.27291e+07,1.30768e+07,1.34167e+07,1.37674e+07,1.4065e+07,1.43475e+07,1.46073e+07,1.48353e+07,1.50235e+07,1.52e+07
119,Afghanistan,AFG,"Population ages 0-4, female (% of female popul...",SP.POP.0004.FE.5Y,18.6835,18.8841,18.9847,19.0072,19.0474,19.2628,...,18.9314,18.7234,18.4509,18.1208,17.6837,17.1508,16.581,16.0515,15.6036,15.1513
120,Afghanistan,AFG,"Population ages 0-4, male (% of male population)",SP.POP.0004.MA.5Y,18.8192,19.0271,19.1298,19.1517,19.1859,19.3819,...,18.7477,18.5498,18.2907,17.9856,17.523,16.985,16.4245,15.9063,15.4615,15.0505
121,Afghanistan,AFG,"Population ages 10-14, female (% of female pop...",SP.POP.1014.FE.5Y,12.3205,12.2839,12.278,12.3122,12.3784,12.4473,...,12.9265,13.1122,13.3253,13.5323,13.6728,13.7715,13.8258,13.8382,13.8146,13.7987
122,Afghanistan,AFG,"Population ages 10-14, male (% of male populat...",SP.POP.1014.MA.5Y,12.4376,12.4218,12.4398,12.4995,12.5921,12.6898,...,12.8434,13.0863,13.3469,13.5844,13.7004,13.7672,13.7872,13.7658,13.7095,13.6913
123,Afghanistan,AFG,"Population ages 15-19, female (% of female pop...",SP.POP.1519.FE.5Y,10.2816,10.251,10.2377,10.2407,10.2508,10.2582,...,10.4307,10.3647,10.3791,10.4776,10.7161,10.991,11.2683,11.5095,11.6952,11.7939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59844,Zimbabwe,ZWE,"Population ages 50-54, female (% of female pop...",SP.POP.5054.FE.5Y,2.61054,2.57425,2.53013,2.48342,2.44202,2.41025,...,2.495,2.46419,2.42379,2.38322,2.37301,2.36833,2.36618,2.36248,2.35641,2.35491
59845,Zimbabwe,ZWE,"Population ages 50-54, male (% of male populat...",SP.POP.5054.MA.5Y,2.45726,2.42408,2.38512,2.3456,2.31325,2.29207,...,1.96538,1.93395,1.89646,1.86086,1.86679,1.88048,1.8992,1.91964,1.94107,1.96789
59846,Zimbabwe,ZWE,"Population ages 55-59, female (% of female pop...",SP.POP.5559.FE.5Y,2.07447,2.05082,2.05324,2.06783,2.07757,2.07453,...,1.79076,1.88208,1.95389,1.98923,2.00839,2.00525,1.98838,1.97064,1.95917,1.95025
59847,Zimbabwe,ZWE,"Population ages 55-59, male (% of male populat...",SP.POP.5559.MA.5Y,1.93949,1.91358,1.91134,1.92082,1.92744,1.92472,...,1.40974,1.46181,1.49907,1.5087,1.51594,1.50935,1.49582,1.48532,1.4831,1.4857
59848,Zimbabwe,ZWE,"Population ages 5-9, female (% of female popul...",SP.POP.0509.FE.5Y,15.8548,15.8586,15.8864,15.9235,15.9468,15.9285,...,13.0987,13.06,13.0411,13.0351,13.035,13.0863,13.1771,13.283,13.3701,13.4362
59849,Zimbabwe,ZWE,"Population ages 5-9, male (% of male population)",SP.POP.0509.MA.5Y,16.2605,16.2474,16.2441,16.2391,16.2189,16.1661,...,13.8554,13.8253,13.8153,13.8154,13.8171,13.8771,13.9806,14.0998,14.1963,14.2504
59850,Zimbabwe,ZWE,"Population ages 60-64, female (% of female pop...",SP.POP.6064.FE.5Y,1.8482,1.80258,1.74014,1.6759,1.62917,1.60837,...,1.44692,1.38411,1.34778,1.34888,1.38032,1.44384,1.52049,1.58531,1.62565,1.63867
59851,Zimbabwe,ZWE,"Population ages 60-64, male (% of male populat...",SP.POP.6064.MA.5Y,1.70705,1.66255,1.60245,1.54105,1.49612,1.47523,...,1.18819,1.1192,1.07108,1.0521,1.05977,1.09269,1.13665,1.1734,1.19402,1.19633
59852,Zimbabwe,ZWE,Population ages 65 and above (% of total),SP.POP.65UP.TO.ZS,2.97995,2.986,3.00045,3.01617,3.02483,3.02386,...,3.11986,3.11399,3.09098,3.04813,3.00816,2.95506,2.89885,2.85273,2.82359,2.81555
59853,Zimbabwe,ZWE,"Population ages 65 and above, female",SP.POP.65UP.FE.IN,116755,121098,126169,131629,137005,142046,...,235720,239848,243236,245623,248141,249983,251840,254755,259340,265709
59854,Zimbabwe,ZWE,"Population ages 65 and above, female (% of total)",SP.POP.65UP.FE.ZS,3.23556,3.23483,3.24444,3.25676,3.26285,3.2598,...,3.44932,3.4495,3.43358,3.39863,3.36094,3.31048,3.25836,3.21957,3.20198,3.20592
59855,Zimbabwe,ZWE,"Population ages 65 and above, male",SP.POP.65UP.MA.IN,96732,100822,105516,110498,115336,119792,...,180170,182374,183653,183751,184638,184747,184586,184912,186150,189032
59856,Zimbabwe,ZWE,"Population ages 65 and above, male (% of total)",SP.POP.65UP.MA.ZS,2.7205,2.73351,2.753,2.77226,2.7837,2.78498,...,2.77352,2.761,2.73026,2.67889,2.63634,2.58043,2.51979,2.46583,2.42443,2.40429
59857,Zimbabwe,ZWE,"Population ages 65 and above, total",SP.POP.65UP.TO,213489,221918,231681,242125,252337,261832,...,415875,422209,426883,429369,432774,434714,436408,439654,445491,454722
59858,Zimbabwe,ZWE,"Population ages 65-69, female (% of female pop...",SP.POP.6569.FE.5Y,1.28854,1.30066,1.32718,1.35596,1.37204,1.36968,...,1.24263,1.2527,1.25007,1.23003,1.18968,1.13699,1.08759,1.06241,1.07051,1.09615
59859,Zimbabwe,ZWE,"Population ages 65-69, male (% of male populat...",SP.POP.6569.MA.5Y,1.15953,1.17309,1.19801,1.22351,1.23673,1.23294,...,1.04754,1.04424,1.02898,0.998584,0.953971,0.899316,0.8471,0.813606,0.805682,0.811572
59860,Zimbabwe,ZWE,"Population ages 70-74, female (% of female pop...",SP.POP.7074.FE.5Y,0.909854,0.894093,0.879815,0.87104,0.873078,0.887434,...,0.934397,0.925197,0.921072,0.922706,0.920944,0.926944,0.933906,0.932766,0.92037,0.888493
59861,Zimbabwe,ZWE,"Population ages 70-74, male (% of male populat...",SP.POP.7074.MA.5Y,0.7778,0.768551,0.75987,0.755399,0.75974,0.774151,...,0.771126,0.764289,0.759302,0.75621,0.750874,0.749642,0.747543,0.737955,0.718707,0.684637
59862,Zimbabwe,ZWE,"Population ages 75-79, female (% of female pop...",SP.POP.7579.FE.5Y,0.587226,0.578886,0.570874,0.564141,0.559213,0.556602,...,0.664665,0.658439,0.652708,0.648308,0.639286,0.629974,0.622639,0.619889,0.622618,0.623365
59863,Zimbabwe,ZWE,"Population ages 75-79, male (% of male populat...",SP.POP.7579.MA.5Y,0.470347,0.467307,0.463426,0.459903,0.457394,0.456647,...,0.517496,0.512751,0.507852,0.503542,0.499517,0.49464,0.490126,0.487267,0.486566,0.484949
59864,Zimbabwe,ZWE,"Population ages 80 and above, female (% of fem...",SP.POP.80UP.FE.5Y,0.449939,0.461191,0.466574,0.465619,0.458521,0.446081,...,0.607625,0.613164,0.609738,0.597583,0.611032,0.616572,0.614229,0.604509,0.588491,0.597907
59865,Zimbabwe,ZWE,"Population ages 80 and above, male (% of male ...",SP.POP.80UP.MA.5Y,0.312824,0.324561,0.331693,0.333455,0.329837,0.321248,...,0.437356,0.439719,0.434129,0.420559,0.43198,0.436829,0.435017,0.427006,0.413475,0.423135
59866,Zimbabwe,ZWE,Population growth (annual %),SP.POP.GROW,3.44181,3.66944,3.82264,3.88679,3.84451,3.72564,...,1.55473,1.70011,1.8425,1.97676,2.10967,2.22831,2.30937,2.3448,2.34564,2.33607
59867,Zimbabwe,ZWE,"Population, female",SP.POP.TOTL.FE.IN,3.6085e+06,3.74357e+06,3.88878e+06,4.04172e+06,4.19894e+06,4.35750e+06,...,6.83382e+06,6.95312e+06,7.08403e+06,7.22711e+06,7.38308e+06,7.55127e+06,7.72904e+06,7.91271e+06,8.09935e+06,8.28809e+06
59868,Zimbabwe,ZWE,"Population, female (% of total)",SP.POP.TOTL.FE.ZS,50.3687,50.3714,50.3627,50.348,50.3337,50.3243,...,51.2668,51.2825,51.2941,51.3059,51.319,51.3314,51.3404,51.3423,51.335,51.3183
59869,Zimbabwe,ZWE,"Population, male",SP.POP.TOTL.MA.IN,3.55568e+06,3.68837e+06,3.83276e+06,3.98584e+06,4.14326e+06,4.30135e+06,...,6.49609e+06,6.60535e+06,6.72657e+06,6.85921e+06,7.00357e+06,7.15956e+06,7.32546e+06,7.49897e+06,7.6781e+06,7.86228e+06
59870,Zimbabwe,ZWE,"Population, male (% of total)",SP.POP.TOTL.MA.ZS,49.6313,49.6286,49.6373,49.652,49.6663,49.6757,...,48.7332,48.7175,48.7059,48.6941,48.681,48.6686,48.6596,48.6577,48.665,48.6817
59871,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,7.16417e+06,7.43194e+06,7.72154e+06,8.02756e+06,8.3422e+06,8.65886e+06,...,1.33299e+07,1.35585e+07,1.38106e+07,1.40863e+07,1.43866e+07,1.47108e+07,1.50545e+07,1.54117e+07,1.57775e+07,1.61504e+07
59908,Zimbabwe,ZWE,"Survival to age 65, female (% of cohort)",SP.DYN.TO65.FE.ZS,61.3073,62.1868,63.0663,62.9993,62.9323,62.8654,...,30.449,34.4049,38.3609,42.3169,46.2729,50.2288,52.1515,54.0741,55.9968,55.9968
59909,Zimbabwe,ZWE,"Survival to age 65, male (% of cohort)",SP.DYN.TO65.MA.ZS,54.1078,54.8049,55.5019,54.6778,53.8536,53.0295,...,25.312,29.0616,32.8112,36.5608,40.3104,44.06,45.6382,47.2163,48.7945,48.7945

In [24]:
df.to_excel('World Development Indicator - Cleaned.xlsx')